website/music/urls.py
from django.conf.urls import url
from . import views

app_name= 'music'
# /music/
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/music/71
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='detail'),
    # music/album/add
    url(r'^album/add/$', views.AlbumCreate.as_view(),name= 'album-add'),


    # music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(),name= 'album-update'),


    # music/album/2/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(),name= 'album-delete'),

    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.song_form, name='create_song'),


    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/music/models.py
# -*- coding: utf-8 -*-
'''from __future__ import unicode_literals'''

from django.db import models
from django.core.urlresolvers import reverse



# Create your models here.
class Album(models.Model):
	artist=models.CharField(max_length=250)
	album_title= models.CharField(max_length=500)
	genre=models.CharField(max_length=100)
	album_logo=models.FileField()

	def get_absolute_url(self):
		return reverse('music:detail',kwargs={'pk': self.pk})

	def __str__(self):
		return self.album_title+' - '+ self.artist

class Song(models.Model):
	album=models.ForeignKey(Album,on_delete=models.CASCADE)
	file_type=models.CharField(max_length=10)
	song_title=models.CharField(max_length=250)

	

	

	def __str__(self):
		return self.song_title

website/music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Album, Song

class UserForm(forms.ModelForm):
	password= forms.CharField(widget=forms.PasswordInput)


	class Meta:
		model= User
		fields=['username','email','password']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'file_type']

website/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from .forms import SongForm, UserForm


class IndexView(generic.ListView):
	template_name= 'music/index.html'
	context_object_name= 'all_albums'

	def get_queryset(self):
		return Album.objects.all()


class DetailView(generic.DetailView):
	model=Album
	template_name='music/detail.html'


class AlbumCreate(CreateView):
	model= Album
	fields=['artist','album_title','genre', 'album_logo']


class AlbumUpdate(UpdateView):
	model= Album
	fields=['artist','album_title','genre', 'album_logo']






class AlbumDelete(DeleteView):
	model= Album
	success_url= reverse_lazy('music:index')

class UserFormView(View):
	form_class=UserForm
	template_name='music/registration_form.html'


#display blank form
	def get(self, request):
		form= self.form_class(None)
		return render(request, self.template_name, {'form' : form})
# process form data
	def post(self, request):
		form=self.form_class(request.POST)

		if form.is_valid():
			user= form.save()

			#cleaned(normalized) dat
			username= form.cleaned_data['username']
			password= form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns user object if credentials are correct
			user=authenticate(username=username,password=password)


			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('music:index')

		return render(request, self.template_name, {'form' : form})




def song_form(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        for s in albums_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'music/song_form.html', context)
        song = form.save(commit=False)
        song.album = album
        '''song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'music/create_song.html', context)'''

        song.save()
        return render(request, 'music/detail.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'music/song_form.html', context)


def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/detail.html', {'album': album})

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
	                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	                {% csrf_token %}
	                {% include 'music/form-template.html' %}
	                <div class="form_group">
	                	<div class="col-sm-offset-2 col-sm-10">
	                		<button type="submit" class=btn btn-success>Submit</button>
	                	</div>
	                </div>


	                </form>




                 </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Xiberr{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container_fluid">

		<!-- Header -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					
				</button>
				<a class="navbar-brand" href="{% url 'music:index'   %}">Xiberr</a>
			</div >
			<!-- items -->
			<div class="collapse navbar-collapse" id="topNavBar">
				
				<ul class="nav navbar-nav">
					<li class="">
						<a href="{% url 'music:index'%}">
							<span class="glyphicon glyphicon-cd" aria-hidden="true" ></span>&nbsp;Albums
						</a>
					</li>
					<li class="">
						<a href="http://www.gaana.com">
							<span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>&nbsp;Gaana
						</a>
					</li>
					<li class="">
						<a href="https://www.saavn.com/">
							<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Saavn
						</a>
					</li>

				</ul>
				
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="{% url 'music:album-add' %} ">
							<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Albums
						</a>
					</li>
					<li class="">
						<a href="https://www.youtube.com/?gl=IN">
							<span class="glyphicon glyphicon-play" aria-hidden="true"></span>&nbsp;YouTube
						</a>
					</li>

				</ul>

			</div>
				
			
		</div>
	</nav>
{% block body %}
{% endblock %}

</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Albums{% endblock %}
{% block body %}

	 <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

	<div class="col-sm-8 col-md-9">

    <ul class="nav nav-pills" style="margin-bottom: 10px;">
                
                <li role="presentation"><a href="{% url 'music:create_song' album.id %}"><button type="button" class="btn btn-success btn-s">Add New Song</button></a></li>
            </ul>

          

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Play</th>
                            <th>Detail</th>                            
                            
                            
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}.{{song.file_type}}</td>
                            <td>
                                    <a href="https://www.youtube.com/results?search_query={{ song.song_title }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>

                               <td>
                                    <form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-trash"></span>&nbsp;
                                        </button>
                                    </form>
                                    
                                </td>

                            
                                </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
{% endblock %}

website/music/templates/music/form-template.html
{% block aform%}
{% for field in form %}

	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<span class="text-danger small"> {{ field.errors }} </span>
	</div>
	<label class="control-label col-sm-2">{{ field.label_tag }}</label>
	<div class="col-sm-10">{{ field }}</div>
		
	</label>
		
	</div>


{%endfor%}
{%endblock%}

website/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

	<ul>
		{% for album in all_albums %}

		<div class="col-sm-10 col-lg-3">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h3>{{ album.album_title }}</h3>
                           <!-- <h4>{{ album.artist }}</h4>-->

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            <a href="{% url 'music:album-update' album.id %}" class="btn btn-primary btn-sm" role="button">Edit</a>






		<!--<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a></li> -->
			<form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
	                                {% csrf_token %}
	                                <input type="hidden" name="album_id" value="{{ album.id }}" />
	                                <button type="submit" class="btn btn-default btn-sm">
	                                    <span class="glyphicon glyphicon-trash"></span>
	                                </button>
	                            </form>
	                            </div>
	                            </div>

	                            </div>
		{% endfor %}
	</ul>


{% endblock %}

website/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                <h3> Create a New Acoount</h3>
	                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	                {% csrf_token %}
	                {% include 'music/form-template.html' %}
	                <div class="form_group">
	                	<div class="col-sm-offset-2 col-sm-10">
	                		<button type="submit" class=btn btn-success>Submit</button>
	                	</div>
	                </div>


	                </form>




                 </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

website/music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
	                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	                {% csrf_token %}
	                {% include 'music/form-template.html' %}
	                <div class="form_group">
	                	<div class="col-sm-offset-2 col-sm-10">
	                		<button type="submit" class=btn btn-success>Submit</button>
	                	</div>
	                </div>


	                </form>




                 </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}